const launcher=document.getElementById('kateLauncher');
const panel=document.getElementById('katePanel');
const closeBtn=document.getElementById('kateClose');
const body=document.getElementById('kateBody');
const form=document.getElementById('kateForm');
const input=document.getElementById('kateInput');
const DART_STATUS_API='https://yvppsjgyedqcvfbhrhrm.supabase.co/functions/v1/kate-dart-status';
const CUSTOMER_UPDATE_API='https://yvppsjgyedqcvfbhrhrm.supabase.co/functions/v1/kate-customer-update';
let kateFlow=null;
const pick=a=>a[Math.floor(Math.random()*a.length)];
function setOpen(open){panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));launcher.setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>input.focus(),100)}
launcher.addEventListener('click',()=>setOpen(!panel.classList.contains('open')));closeBtn.addEventListener('click',()=>setOpen(false));
const replies={problem:'I’m here with you. Tell me what happened with the delivery and I’ll help you figure out the next step.',quote:'Absolutely! Tell me the airport, delivery area, expected volume, and service you need and I’ll help with the quote details.',areas:'K&E provides airport luggage and last-mile delivery services. Tell me where you need service and I’ll help you out.',drivers:'Thinking about joining the K&E family? 😄 I can help with our independent driver opportunities.',other:'I’m KatE, your K&E Delivery Assistant. I can help with bag status, attempted deliveries, delivery problems, quotes, service areas, and driver opportunities.'};
function addMessage(text,type='bot'){const msg=document.createElement('div');msg.className='kate-message '+(type==='user'?'kate-user':'kate-bot');msg.textContent=text;body.appendChild(msg);body.scrollTop=body.scrollHeight}
function startDeliveryLookup(mode='status'){kateFlow={mode,step:'order',orderNumber:'',lastName:'',confirmedAddress:'',confirmedPhone:'',deliveryInstructions:'',gateCode:'',lastData:null};addMessage(mode==='attempted'?'I can check that for you. First, send me your K&E delivery/order number and I’ll take a look.':'Of course! Let me check on your bag. First, send me your K&E delivery/order number.');input.placeholder='Enter delivery/order number…'}
function resetFlow(){kateFlow=null;input.placeholder='Type a message to KatE…'}
function friendlyStatus(data){const status=(data.status||'').trim().toLowerCase();const when=data.lastUpdate?` The latest update was ${data.lastUpdate}.`:'';if(!status)return `I found it! Your baggage is ready for pickup, but a driver hasn’t been assigned yet.${data.pickupDate||data.pickupTime?` The pickup is listed for ${[data.pickupDate,data.pickupTime].filter(Boolean).join(' at ')}.`:''}`;if(status==='delivered')return pick([`Good news! 🎉 Your baggage has been delivered.${data.deliveredAt?` It was completed ${data.deliveredAt}.`:when}`,`Delivery complete! 🙌 Your bag made it.${data.deliveredAt?` It was delivered ${data.deliveredAt}.`:when}`]);if(status==='attempted')return `I found an attempted delivery on your order.${data.attemptedAt?` The attempt was ${data.attemptedAt}.`:when} Let’s make sure we have everything the driver needs for the next attempt.`;if(status==='out for delivery'||status==='out_for_delivery')return pick([`Good news—your baggage is out for delivery! 🚙💨${when}`,`Your bag is officially on the move! 🚙💨 It’s out for delivery.${when}`]);if(status==='assigned')return `Great! A driver has been assigned to your delivery and it’s being prepared to go out.${when}`;if(status==='picked up'||status==='picked_up')return pick([`Your baggage has been picked up by K&E and is moving through the delivery process.${when}`,`We’ve got your bag! 🙌 It has been picked up by K&E and is moving through the delivery process.${when}`]);if(status==='unassign driver'||status==='unassigned driver')return `I found your delivery. Your baggage is ready for pickup, but a driver hasn’t been assigned yet.${when}`;return `I found your delivery. Its current status is ${data.status}.${when}`}
async function lookupDelivery(orderNumber,lastName,mode){addMessage(pick(['Give me just a moment while I check the live delivery system…','Let me take a quick look at the live delivery system for you…']));try{const response=await fetch(DART_STATUS_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber,lastName,requestType:mode})});if(response.status===404){addMessage('Hmm, I couldn’t find a delivery matching those details. Double-check the order number and last name for me and we can try again.');resetFlow();return}if(response.status===401||response.status===403){addMessage('I found the lookup, but those details didn’t verify the delivery. Please double-check the order number and passenger/customer last name.');resetFlow();return}if(!response.ok)throw new Error('lookup_failed');const data=await response.json();kateFlow.lastData=data;addMessage(friendlyStatus(data));kateFlow.step='address';addMessage('While I have you here, let’s make sure the driver has everything needed for a smooth delivery. 😊 Can you confirm the full delivery address?');input.placeholder='Confirm delivery address…'}catch(e){addMessage('I’m having trouble reaching the live delivery system right now. I don’t want to guess about your bag, so please try me again shortly or contact K&E Delivery for help.');resetFlow()}}
function friendlyClosing(){return pick([`You’re all set! I’ve saved the delivery details you provided so the K&E team has what they need. We’ll do our best to make the delivery go smoothly. 😊 Is there anything else I can help you with?`,`All set! 🙌 I’ve saved the information you provided for the K&E team. Now we just need to get that bag to you! Is there anything else I can help with?`,`You’re all set! And thank you for reaching out to the best part of the K&E family—which is obviously me. 🤣 Just kidding! 😂 I’ve saved the delivery information you provided. Is there anything else I can help you with?`,`Perfect, I’ve got it! Your delivery details are saved for the K&E team. I’ll try not to take all the credit when everything goes smoothly. 😂 Anything else I can help you with?`])}
async function saveCustomerUpdate(){addMessage(pick(['Perfect—let me save that for the K&E team.','Got it! I’m saving those details for the K&E team now.']));try{const r=await fetch(CUSTOMER_UPDATE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber:kateFlow.orderNumber,lastName:kateFlow.lastName,confirmedAddress:kateFlow.confirmedAddress,confirmedPhone:kateFlow.confirmedPhone,deliveryInstructions:kateFlow.deliveryInstructions,gateCode:kateFlow.gateCode})});if(!r.ok)throw new Error('save_failed');addMessage(friendlyClosing())}catch(e){addMessage('I verified your delivery, but I couldn’t save the extra delivery details right now. Please contact K&E Delivery so the team can confirm them with you.')}resetFlow()}
function flowQuestion(text){if(!kateFlow||!kateFlow.lastData)return false;const q=text.toLowerCase();const d=kateFlow.lastData;if(/which address|what address|address.*have|where.*deliver/.test(q)){if(d.deliveryAddress){addMessage(`The delivery address I have is ${d.deliveryAddress}. Does that look correct?`)}else if(d.city||d.zip){addMessage(`I can see the delivery is going to ${[d.city,d.zip].filter(Boolean).join(', ')}, but the street address is not included in the summary I can see yet. I’m keeping your place in the conversation while we confirm it.`)}else{addMessage('I can verify the delivery, but the street address is not showing in the summary I have yet. I’m keeping your place right here while we confirm it.')}return true}if(/what.*phone|which.*phone|phone.*have|number.*have/.test(q)){if(d.contactPhone)addMessage(`The contact number I have is ${d.contactPhone}. Is that still the best number for the driver?`);else addMessage('The phone number isn’t showing in the delivery summary I have yet. You can give me the best number and I’ll save it for the K&E team.');return true}if(/what.*status|where.*bag|where.*delivery|status/.test(q)){addMessage(friendlyStatus(d));return true}if(/you.*not answering|answer my question|that.*not what i asked|not what i asked/.test(q)){addMessage('You’re right—I jumped ahead. 😅 Ask me your question again and I’ll answer it before we continue.');return true}return false}
async function handleFlowInput(text){if(!kateFlow)return false;if(flowQuestion(text))return true;if(kateFlow.step==='order'){kateFlow.orderNumber=text.trim();kateFlow.step='lastName';addMessage(pick(['Got it. Now send me the passenger/customer last name so I can verify the delivery.','Perfect. One more thing—what’s the passenger/customer last name on the delivery?']));input.placeholder='Enter last name…';return true}if(kateFlow.step==='lastName'){kateFlow.lastName=text.trim();await lookupDelivery(kateFlow.orderNumber,kateFlow.lastName,kateFlow.mode);return true}if(kateFlow.step==='address'){kateFlow.confirmedAddress=text.trim();kateFlow.step='phone';addMessage('Got it. 👍 What’s the best phone number for the driver to use if they need to reach you?');input.placeholder='Confirm contact number…';return true}if(kateFlow.step==='phone'){kateFlow.confirmedPhone=text.trim();kateFlow.step='instructions';addMessage('Perfect. Any delivery instructions that would help the driver—where to leave the baggage, how to find the residence, anything like that? If not, just type “none.”');input.placeholder='Delivery instructions or none…';return true}if(kateFlow.step==='instructions'){kateFlow.deliveryInstructions=/^none$/i.test(text.trim())?'':text.trim();kateFlow.step='gate';addMessage('Last one, I promise. 😄 Is there a community gate code, building access code, or anything else the driver needs to get in? If not, type “none.”');input.placeholder='Gate/access code or none…';return true}if(kateFlow.step==='gate'){kateFlow.gateCode=/^none$/i.test(text.trim())?'':text.trim();await saveCustomerUpdate();return true}return false}
function answerText(text){const q=text.toLowerCase();if(q.includes('attempt')||q.includes('nobody home')||q.includes('missed delivery')){startDeliveryLookup('attempted');return null}if(q.includes('status')||q.includes('where')||q.includes('track')||q.includes('bag')){startDeliveryLookup('status');return null}if(q.includes('problem')||q.includes('damage')||q.includes('wrong')||q.includes('issue'))return replies.problem;if(q.includes('quote')||q.includes('price')||q.includes('cost')||q.includes('rate'))return replies.quote;if(q.includes('area')||q.includes('city')||q.includes('serve')||q.includes('service'))return replies.areas;if(q.includes('driver')||q.includes('job')||q.includes('work')||q.includes('apply'))return replies.drivers;if(/^(hi|hello|hey|hola)\b/.test(q))return pick([`Hey! 👋 I’m KatE. What can I help you with today?`,`Hi! 😊 KatE here. How can I help?`,`Hey there! You’ve got KatE. What can I do for you?`]);if(q.includes('thank'))return pick([`You’re very welcome! 😊`,`Anytime! That’s what I’m here for. 💙`,`You got it! 😊`]);return pick([`I’m here to help. You can ask me about your bag status, an attempted delivery, a delivery problem, quotes, service areas, or driver opportunities.`,`Tell me what you need and I’ll see what I can do. 😊 I can help with delivery status, delivery issues, quotes, service areas, and driver opportunities.`])}
document.querySelectorAll('#kateOptions button').forEach(btn=>btn.addEventListener('click',()=>{const topic=btn.dataset.topic;if(topic==='status'||topic==='attempted'){startDeliveryLookup(topic);return}addMessage(replies[topic])}));
form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text,'user');input.value='';if(await handleFlowInput(text))return;const reply=answerText(text);if(reply)setTimeout(()=>addMessage(reply),180)});